---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-oci-demo-november-15
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: latest
  url: oci://ghcr.io/juozasg/flux-oci-demo-november-15

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-oci-demo-november-15
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/demo
  prune: false
  sourceRef:
    kind: OCIRepository
    name: flux-oci-demo-november-15
  targetNamespace: flux-system

